plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
}

android {
    namespace = "in.santhaliastore.ratecard"
    compileSdk = 34

    defaultConfig {
        applicationId = "in.santhaliastore.ratecard"
        minSdk = 24
        targetSdk = 34
        // Bumped from 1 / "1.0.0" to invalidate launcher icon caches on
        // MIUI / One UI / themed-icon launchers that key the cached icon
        // by package + versionCode + signature.
        versionCode = 6
        versionName = "1.0.5"

        // Vector drawables — supportLibrary lets older devices render them too.
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    // KSP arguments live at the top level of `android {}` is wrong — the
    // `ksp { ... }` extension is provided by the KSP plugin and lives at
    // the project script's top level, configured below.

    // -----------------------------------------------------------------
    // Stable signing for sideloaded debug + release APKs.
    //
    // Without a committed keystore, AGP generates a fresh debug keystore
    // per build environment. That means an APK from one CI run cannot
    // install on top of a previous APK (different cert), forcing the
    // user to uninstall — which wipes their local Room database.
    //
    // Solution: commit a known-good keystore at android-app/keystore/
    // (bootstrapped once via the bootstrap-debug-keystore workflow) and
    // sign all builds with it. The committed keystore is *only* used for
    // sideload distribution — its password is intentionally non-secret
    // because there's no Play Store distribution to protect.
    //
    // If the keystore file is missing (fresh checkout, before bootstrap)
    // we silently fall back to AGP's default debug signing, so the build
    // still produces an installable APK — just one whose updates may
    // require uninstall first.
    // -----------------------------------------------------------------
    val stableKeystoreFile = rootProject.file("keystore/santhalia.keystore")
    if (stableKeystoreFile.exists()) {
        signingConfigs {
            create("santhalia") {
                storeFile = stableKeystoreFile
                storePassword = "santhalia"
                keyAlias = "santhalia"
                keyPassword = "santhalia"
            }
        }
    }

    buildFeatures {
        compose = true
        // BuildConfig is generated by default at AGP 8.x for application modules,
        // we don't need anything fancy in it but keep it on for any debug flags.
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // java.time on minSdk 24 needs core library desugaring. Cheap and
        // reliable — adds ~25KB to the APK in exchange for full java.time
        // support down to API 24.
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = "17"
        // Free up some compile warnings — the Kotlin team flips deprecations
        // around between Compose plugin versions and we want a clean build.
        freeCompilerArgs += listOf(
            "-opt-in=kotlin.RequiresOptIn",
            "-opt-in=androidx.compose.material3.ExperimentalMaterial3Api",
            "-opt-in=androidx.compose.foundation.ExperimentalFoundationApi"
        )
    }

    // Make sure the Room schemas/ directory is shipped as part of the source
    // tree so migrations can reference older versions during code review.
    sourceSets {
        getByName("androidTest") {
            assets.srcDirs("$projectDir/schemas")
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
            isShrinkResources = false
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
            // Use the stable keystore if it has been bootstrapped so
            // updates install in place without wiping local data.
            signingConfigs.findByName("santhalia")?.let { signingConfig = it }
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            // Prefer the stable santhalia keystore; fall back to AGP's
            // default debug signing so the workflow still produces an
            // installable APK on a fresh checkout.
            signingConfig = signingConfigs.findByName("santhalia")
                ?: signingConfigs.getByName("debug")
        }
    }

    packaging {
        resources {
            excludes += setOf(
                "/META-INF/{AL2.0,LGPL2.1}",
                "/META-INF/DEPENDENCIES",
                "/META-INF/LICENSE",
                "/META-INF/LICENSE.txt",
                "/META-INF/NOTICE",
                "/META-INF/NOTICE.txt"
            )
        }
    }
}

// Pass the Room schema export dir into the KSP processor. The `ksp {}`
// extension is contributed by the com.google.devtools.ksp plugin and
// must live at the top level of the build script, not inside `android`.
ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
    arg("room.incremental", "true")
    arg("room.generateKotlin", "true")
}

dependencies {
    // Core / Compose BOM aligned versions
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)

    val composeBom = platform(libs.androidx.compose.bom)
    implementation(composeBom)
    androidTestImplementation(composeBom)

    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)

    // Navigation
    implementation(libs.androidx.navigation.compose)

    // Room — KSP, not KAPT
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    implementation(libs.androidx.room.paging)
    ksp(libs.androidx.room.compiler)

    // Paging
    implementation(libs.androidx.paging.runtime)
    implementation(libs.androidx.paging.compose)

    // DataStore
    implementation(libs.androidx.datastore.preferences)

    // WorkManager
    implementation(libs.androidx.work.runtime.ktx)

    // Networking + JSON
    implementation(libs.retrofit)
    implementation(libs.retrofit.converter.moshi)
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging)
    implementation(libs.moshi)
    implementation(libs.moshi.kotlin)

    // Coroutines
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)

    // Debug / tooling
    debugImplementation(libs.androidx.compose.ui.tooling)

    // Core library desugaring for java.time / java.util.Optional on minSdk 24.
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    // Tests (minimal — production app, no fancy harness)
    testImplementation(libs.junit)
}
