package `in`.santhaliastore.ratecard.sync

import com.squareup.moshi.JsonClass

/**
 * DTOs shipped to / received from the Apps Script web app. Field
 * names MUST exactly match the contract documented in apps-script/Code.gs:
 *
 *   POST { action, payload }
 *
 * Anything renamed here breaks the cloud sync silently. Treat with care.
 */

/** Top-level request envelope: `{ "action": "...", "payload": {...} }`. */
@JsonClass(generateAdapter = true)
data class SyncRequest<T>(
    val action: String,
    val payload: T
)

/** Server response envelope. `errors` is omitted when everything succeeded. */
@JsonClass(generateAdapter = true)
data class SyncResponse(
    val ok: Boolean,
    val processed: Int,
    val action: String? = null,
    val schemaVersion: Int? = null,
    val time: String? = null,
    val errors: List<SyncError>? = null
)

@JsonClass(generateAdapter = true)
data class SyncError(
    val index: Int,
    val key: String?,
    val message: String
)

/**
 * Health check payload — empty per the contract.
 *
 * Moshi's reflective adapter (KotlinJsonAdapterFactory) serialises
 * a no-arg class as an empty `{}`, which is exactly what the server
 * expects.
 */
class HealthPayload

/** `upsertItem` payload. `unit` is nullable. */
@JsonClass(generateAdapter = true)
data class UpsertItemPayload(
    val code: String,
    val name: String,
    val unit: String?,
    val updatedAt: String
)

/** `deleteItem` payload. */
@JsonClass(generateAdapter = true)
data class DeleteItemPayload(
    val code: String,
    val updatedAt: String
)

/**
 * `upsertEntry` payload. `quantity`, `supplier`, `notes` nullable.
 *
 * `quantity` is a free-form String so kirana shop owners can record
 * informal units like "5 kg" or "1 packet" alongside plain numbers.
 * The Apps Script endpoint stores it verbatim.
 */
@JsonClass(generateAdapter = true)
data class UpsertEntryPayload(
    val entryId: String,
    val itemCode: String,
    val date: String,
    val pricePerUnit: Double,
    val quantity: String?,
    val supplier: String?,
    val notes: String?,
    val updatedAt: String
)

/** `deleteEntry` payload. */
@JsonClass(generateAdapter = true)
data class DeleteEntryPayload(
    val entryId: String,
    val updatedAt: String
)

/**
 * `bulkSync` payload. The server caps total changes at 200 per
 * call (see apps-script BULK_LIMIT) so the worker batches accordingly.
 *
 * `bills` / `deletedBills` ride the same envelope as items + entries —
 * no separate sync action — so a single round-trip flushes every kind
 * of pending mutation. Defaults are empty lists so older call sites
 * that don't yet pass bills still compile during the rollout.
 */
@JsonClass(generateAdapter = true)
data class BulkSyncPayload(
    val items: List<UpsertItemPayload>,
    val entries: List<UpsertEntryPayload>,
    val deletedItems: List<DeleteItemPayload>,
    val deletedEntries: List<DeleteEntryPayload>,
    val bills: List<UpsertBillPayload> = emptyList(),
    val deletedBills: List<DeleteBillPayload> = emptyList()
)

/**
 * A single uncaught-exception record captured by the in-process crash
 * handler. Stored locally as one JSON line per event in
 * `<filesDir>/crashes.log`, then drained to the Apps Script `Crashes`
 * tab on the next successful sync.
 *
 * Field names are the wire contract — renaming any of them silently
 * desynchronises the spreadsheet columns. `CrashEventTest` pins them.
 *
 *   - `crashId`       UUID v4 generated by the phone; server dedups on it.
 *   - `timestamp`     ISO 8601 with `Z`, matching `updatedAt` style.
 *   - `appVersion`    BuildConfig.VERSION_NAME at the time of the crash.
 *   - `appVersionCode` BuildConfig.VERSION_CODE.
 *   - `androidVersion` "<release> (API <sdk>)".
 *   - `deviceModel`   "<manufacturer> <model>".
 *   - `threadName`    The thread that died.
 *   - `message`       Top-level Throwable message (may be empty).
 *   - `stackTrace`    Full stack, truncated at 8 KB on a line boundary
 *                     so a runaway loop can't blow up the sheet cell.
 */
@JsonClass(generateAdapter = true)
data class CrashEvent(
    val crashId: String,
    val timestamp: String,
    val appVersion: String,
    val appVersionCode: Int,
    val androidVersion: String,
    val deviceModel: String,
    val threadName: String,
    val message: String,
    val stackTrace: String
)

/**
 * `logCrashes` payload. Capped at 50 events per call client-side —
 * if a phone has more pending crashes than that we have a bigger
 * problem than logging speed.
 */
@JsonClass(generateAdapter = true)
data class LogCrashesPayload(
    val crashes: List<CrashEvent>
)

/* -------------------- pull / bidirectional sync ----------------------- */

/**
 * `pullChanges` request payload.
 *
 * `sinceCursor` is whatever opaque token the server handed back on the
 * previous pull (empty string on a fresh install — the server then
 * returns the entire dataset). The client never inspects it; it just
 * round-trips it. See [PullChangesResponse.cursor].
 */
@JsonClass(generateAdapter = true)
data class PullChangesPayload(val sinceCursor: String)

/**
 * `pullChanges` response.
 *
 * `cursor` is opaque to the client — store it verbatim and pass it
 * back next time. `schemaVersion` and `time` mirror the existing
 * [SyncResponse] envelope shape for diagnostics; they're not
 * load-bearing client-side.
 */
@JsonClass(generateAdapter = true)
data class PullChangesResponse(
    val ok: Boolean,
    val items: List<PulledItem>,
    val entries: List<PulledEntry>,
    val cursor: String,
    val schemaVersion: Int? = null,
    val time: String? = null,
    // Defaulted so a server that hasn't been updated to the bills-aware
    // build yet still deserialises cleanly into this DTO — it simply
    // emits no bills and the client applies an empty list.
    val bills: List<PulledBill> = emptyList()
)

/**
 * A single item row pulled from the server.
 *
 * `updatedAt` is the device-local timestamp from the last writer
 * (used for last-writer-wins conflict resolution against the local
 * row's `updatedAt`). `serverUpdatedAt` is informational only — the
 * cursor handles incremental progress.
 */
@JsonClass(generateAdapter = true)
data class PulledItem(
    val code: String,
    val name: String,
    val unit: String?,
    val updatedAt: String,
    val deleted: Boolean,
    val serverUpdatedAt: String
)

/**
 * A single purchase entry pulled from the server. Mirrors
 * [PulledItem] in the conflict / cursor semantics.
 */
@JsonClass(generateAdapter = true)
data class PulledEntry(
    val entryId: String,
    val itemCode: String,
    val date: String,
    val pricePerUnit: Double,
    val quantity: String?,
    val supplier: String?,
    val notes: String?,
    val updatedAt: String,
    val deleted: Boolean,
    val serverUpdatedAt: String
)

/* ----------------------------- bills ---------------------------------- */

/**
 * `upsertBill` payload — mirror of the `bills` sheet row.
 *
 * `imageFileIds` is a comma-separated list of Google Drive file IDs.
 * The empty string means "no images attached" (NOT nullable — see the
 * matching column comment on [in.santhaliastore.ratecard.data.db.entity.BillEntity]).
 *
 * Deliberately omitted: `localImagePaths`. The local cache paths are
 * meaningless on any other device — syncing them would actively break
 * the receiver's image cache lookups. Local-only metadata never
 * crosses the wire.
 */
@JsonClass(generateAdapter = true)
data class UpsertBillPayload(
    val id: String,
    val date: String,
    val supplier: String?,
    val totalAmount: Double?,
    val notes: String?,
    val imageFileIds: String,
    val updatedAt: String
)

/** `deleteBill` payload. */
@JsonClass(generateAdapter = true)
data class DeleteBillPayload(
    val id: String,
    val updatedAt: String
)

/**
 * A single bill row pulled from the server. Mirrors [PulledItem] /
 * [PulledEntry] in the conflict / cursor semantics.
 */
@JsonClass(generateAdapter = true)
data class PulledBill(
    val id: String,
    val date: String,
    val supplier: String?,
    val totalAmount: Double?,
    val notes: String?,
    val imageFileIds: String,
    val updatedAt: String,
    val deleted: Boolean,
    val serverUpdatedAt: String
)

/* ---------------------- bill image upload / delete -------------------- */

/**
 * `uploadBillImage` payload. The Apps Script side accepts a base64
 * blob, writes it to a fixed Drive folder, and returns the file id
 * plus a viewable URL.
 *
 * Base64 is the lowest-common-denominator transport — Apps Script's
 * web-app endpoint doesn't accept multipart uploads cleanly. The
 * client splits images larger than the server's body cap into one
 * payload per image (each bill page is a separate POST).
 *
 *   - `billId`     UUID of the bill this image belongs to. Server
 *                  uses it as the file-name prefix on Drive so an
 *                  admin can correlate Drive ↔ sheet by eye.
 *   - `fileName`   Original filename hint (e.g. "bill-page1.jpg").
 *                  Server is free to mangle it for uniqueness.
 *   - `mimeType`   `image/jpeg` or `image/png` — Drive needs this to
 *                  set the correct MIME on the uploaded file.
 *   - `dataBase64` Raw image bytes, base64-encoded without any data:
 *                  URL prefix.
 */
@JsonClass(generateAdapter = true)
data class UploadBillImagePayload(
    val billId: String,
    val fileName: String,
    val mimeType: String,
    val dataBase64: String
)

/**
 * `uploadBillImage` response. Mirrors [SyncResponse]'s shape but adds
 * the Drive file metadata we need to wire the upload back into the
 * bill row.
 *
 *   - `fileId`  Drive file id — append to the bill's `imageFileIds`
 *               CSV on success.
 *   - `viewUrl` Direct-view URL the UI can deep-link to when the
 *               local cached copy is missing.
 */
@JsonClass(generateAdapter = true)
data class UploadBillImageResponse(
    val ok: Boolean,
    val fileId: String?,
    val viewUrl: String?,
    val time: String? = null,
    val errors: List<SyncError>? = null
)

/**
 * `deleteBillImage` payload. The server removes the Drive file (or
 * tombstones it server-side, depending on the Apps Script policy) and
 * the standard [SyncResponse] envelope reports success.
 */
@JsonClass(generateAdapter = true)
data class DeleteBillImagePayload(
    val fileId: String
)
