package `in`.santhaliastore.ratecard.sync

import com.squareup.moshi.JsonClass

/**
 * DTOs shipped to / received from the Apps Script web app. Field
 * names MUST exactly match the contract documented in apps-script/Code.gs:
 *
 *   POST { action, payload }
 *
 * Anything renamed here breaks the cloud sync silently. Treat with care.
 */

/** Top-level request envelope: `{ "action": "...", "payload": {...} }`. */
@JsonClass(generateAdapter = true)
data class SyncRequest<T>(
    val action: String,
    val payload: T
)

/** Server response envelope. `errors` is omitted when everything succeeded. */
@JsonClass(generateAdapter = true)
data class SyncResponse(
    val ok: Boolean,
    val processed: Int,
    val action: String? = null,
    val schemaVersion: Int? = null,
    val time: String? = null,
    val errors: List<SyncError>? = null
)

@JsonClass(generateAdapter = true)
data class SyncError(
    val index: Int,
    val key: String?,
    val message: String
)

/**
 * Health check payload — empty per the contract.
 *
 * Moshi's reflective adapter (KotlinJsonAdapterFactory) serialises
 * a no-arg class as an empty `{}`, which is exactly what the server
 * expects.
 */
class HealthPayload

/** `upsertItem` payload. `unit` is nullable. */
@JsonClass(generateAdapter = true)
data class UpsertItemPayload(
    val code: String,
    val name: String,
    val unit: String?,
    val updatedAt: String
)

/** `deleteItem` payload. */
@JsonClass(generateAdapter = true)
data class DeleteItemPayload(
    val code: String,
    val updatedAt: String
)

/** `upsertEntry` payload. `quantity`, `supplier`, `notes` nullable. */
@JsonClass(generateAdapter = true)
data class UpsertEntryPayload(
    val entryId: String,
    val itemCode: String,
    val date: String,
    val pricePerUnit: Double,
    val quantity: Double?,
    val supplier: String?,
    val notes: String?,
    val updatedAt: String
)

/** `deleteEntry` payload. */
@JsonClass(generateAdapter = true)
data class DeleteEntryPayload(
    val entryId: String,
    val updatedAt: String
)

/**
 * `bulkSync` payload. The server caps total changes at 200 per
 * call (see apps-script BULK_LIMIT) so the worker batches accordingly.
 */
@JsonClass(generateAdapter = true)
data class BulkSyncPayload(
    val items: List<UpsertItemPayload>,
    val entries: List<UpsertEntryPayload>,
    val deletedItems: List<DeleteItemPayload>,
    val deletedEntries: List<DeleteEntryPayload>
)

/**
 * A single uncaught-exception record captured by the in-process crash
 * handler. Stored locally as one JSON line per event in
 * `<filesDir>/crashes.log`, then drained to the Apps Script `Crashes`
 * tab on the next successful sync.
 *
 * Field names are the wire contract — renaming any of them silently
 * desynchronises the spreadsheet columns. `CrashEventTest` pins them.
 *
 *   - `crashId`       UUID v4 generated by the phone; server dedups on it.
 *   - `timestamp`     ISO 8601 with `Z`, matching `updatedAt` style.
 *   - `appVersion`    BuildConfig.VERSION_NAME at the time of the crash.
 *   - `appVersionCode` BuildConfig.VERSION_CODE.
 *   - `androidVersion` "<release> (API <sdk>)".
 *   - `deviceModel`   "<manufacturer> <model>".
 *   - `threadName`    The thread that died.
 *   - `message`       Top-level Throwable message (may be empty).
 *   - `stackTrace`    Full stack, truncated at 8 KB on a line boundary
 *                     so a runaway loop can't blow up the sheet cell.
 */
@JsonClass(generateAdapter = true)
data class CrashEvent(
    val crashId: String,
    val timestamp: String,
    val appVersion: String,
    val appVersionCode: Int,
    val androidVersion: String,
    val deviceModel: String,
    val threadName: String,
    val message: String,
    val stackTrace: String
)

/**
 * `logCrashes` payload. Capped at 50 events per call client-side —
 * if a phone has more pending crashes than that we have a bigger
 * problem than logging speed.
 */
@JsonClass(generateAdapter = true)
data class LogCrashesPayload(
    val crashes: List<CrashEvent>
)

/* -------------------- pull / bidirectional sync ----------------------- */

/**
 * `pullChanges` request payload.
 *
 * `sinceCursor` is whatever opaque token the server handed back on the
 * previous pull (empty string on a fresh install — the server then
 * returns the entire dataset). The client never inspects it; it just
 * round-trips it. See [PullChangesResponse.cursor].
 */
@JsonClass(generateAdapter = true)
data class PullChangesPayload(val sinceCursor: String)

/**
 * `pullChanges` response.
 *
 * `cursor` is opaque to the client — store it verbatim and pass it
 * back next time. `schemaVersion` and `time` mirror the existing
 * [SyncResponse] envelope shape for diagnostics; they're not
 * load-bearing client-side.
 */
@JsonClass(generateAdapter = true)
data class PullChangesResponse(
    val ok: Boolean,
    val items: List<PulledItem>,
    val entries: List<PulledEntry>,
    val cursor: String,
    val schemaVersion: Int? = null,
    val time: String? = null
)

/**
 * A single item row pulled from the server.
 *
 * `updatedAt` is the device-local timestamp from the last writer
 * (used for last-writer-wins conflict resolution against the local
 * row's `updatedAt`). `serverUpdatedAt` is informational only — the
 * cursor handles incremental progress.
 */
@JsonClass(generateAdapter = true)
data class PulledItem(
    val code: String,
    val name: String,
    val unit: String?,
    val updatedAt: String,
    val deleted: Boolean,
    val serverUpdatedAt: String
)

/**
 * A single purchase entry pulled from the server. Mirrors
 * [PulledItem] in the conflict / cursor semantics.
 */
@JsonClass(generateAdapter = true)
data class PulledEntry(
    val entryId: String,
    val itemCode: String,
    val date: String,
    val pricePerUnit: Double,
    val quantity: Double?,
    val supplier: String?,
    val notes: String?,
    val updatedAt: String,
    val deleted: Boolean,
    val serverUpdatedAt: String
)
